services:
  app:
    build: .
    container_name: geotrack_app
    ports:
      - "8080:8080"
      - "8443:8443"
      - "443:443"
    networks:
      - app_network
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    volumes:
      - ./app/logs:/app/logs
      - /etc/letsencrypt/live/geotrack.ininetech.com.br:/etc/letsencrypt/live/geotrack.ininetech.com.br
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    command: ["redis-server", "--appendonly", "no"]

volumes:
  redis_data:
    driver: local

networks:
  app_network:
    driver: bridge
