name: Deploy Application

on:
  push:
    branches:
      - main # Dispara o workflow em pushes no branch `main`.
      - sprint-4

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar repositório
      uses: actions/checkout@v3

    - name: Configurar chave SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  

    - name: Testar conexão SSH
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@152.67.61.112 "echo 'Conexão SSH estabelecida com sucesso!'"

    - name: Executar script remoto
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@152.67.61.112 "cd /home/ubuntu && export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v22.11.0/bin && source ~/.bashrc && ./executa.sh"
